//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniconGS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfiguratorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfiguratorSettings defaultInstance = ((ConfiguratorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfiguratorSettings())));
        //public string ipSettings;

        public static ConfiguratorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ipSettings {
            get {
                return ((string)(this["ipSettings"]));
            }
            set {
                this["ipSettings"] = value;
            }
        }
    }
}
